{
  "openapi": "3.0.3",
  "info": {
    "title": "Hyarcade API",
    "description": "# Introduction\n This is backend api for all Hyarcade systems\n [Hyarcade](https://hyarcade.xyz/) - [GitHub Repo](https://github.com/eatmyvenom/hyarcade)\n## Limits\n Any IP address has a default rate limit of 120 requests per minute.\n\n### Response Format\n Responses are served in JSON format.\n\n# Authentication\n\n<!-- ReDoc-Inject: <security-definitions> -->",
    "version": "v1",
    "contact": {
      "name": "EatMyVenom",
      "url": "https://vnmm.dev",
      "email": "v.nmm@outlook.net"
    }
  },
  "servers": [
    {
      "url": "https://api.hyarcade.xyz"
    }
  ],
  "components": {
    "securitySchemes": {
      "Api Key": {
        "type": "apiKey",
        "in": "header",
        "name": "key",
        "description": "Not needed in most use cases, the rate limits are 120/minute per IP. If you want to use more than that contact eatmyvenom."
      },
      "Database Pass": {
        "type": "Override",
        "in": "header",
        "name": "authorization",
        "description": "A key to use internal systems and override rate limits, meant for any companion systems like Arcade Bot."
      }
    },
    "responses": {
      "RateLimited": {
        "description": "A request limit has been reached, this can be due to the limit on the IP address being hit.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": false
                },
                "reason": {
                  "type": "string",
                  "example": "RATELIMIT"
                },
                "timeout": {
                  "type": "number",
                  "example": 30000
                }
              }
            }
          }
        }
      },
      "MissingPage": {
        "description": "The page provided does not exist.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "example": false
                },
                "cause": {
                  "type": "string",
                  "example": "Page not found"
                }
              }
            }
          }
        }
      }
    },
    "schemas": {
      "Booster": {
        "properties": {
          "_id": {
            "type": "string",
            "format": "objectid"
          },
          "purchaserUuid": {
            "type": "string",
            "format": "uuid",
            "example": "ad8fefaa8351454bb739a4eaa872173f"
          },
          "amount": {
            "type": "number"
          },
          "originalLength": {
            "type": "integer"
          },
          "length": {
            "type": "integer"
          },
          "gameType": {
            "type": "integer"
          },
          "dateActivated": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "ActiveBooster": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Booster"
          },
          {
            "type": "object",
            "properties": {
              "stacked": {
                "type": "array",
                "nullable": true,
                "items": {
                  "type": "string",
                  "description": "UUID of the player in a dashed format",
                  "format": "uuid",
                  "example": "ad8fefaa-8351-454b-b739-a4eaa872173f"
                }
              }
            }
          }
        ]
      },
      "QueuedBooster": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Booster"
          },
          {
            "type": "object",
            "properties": {
              "stacked": {
                "type": "boolean",
                "nullable": true
              }
            }
          }
        ]
      },
      "SkyBlockAuction": {
        "properties": {
          "_id": {
            "type": "string",
            "format": "objectid"
          },
          "uuid": {
            "type": "string",
            "format": "uuid"
          },
          "auctioneer": {
            "type": "string",
            "format": "uuid"
          },
          "profile_id": {
            "type": "string",
            "format": "uuid"
          },
          "coop": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uuid"
            }
          },
          "start": {
            "type": "number",
            "format": "int64"
          },
          "end": {
            "type": "number",
            "format": "int64"
          },
          "item_name": {
            "type": "string"
          },
          "item_lore": {
            "type": "string"
          },
          "extra": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "tier": {
            "type": "string"
          },
          "starting_bid": {
            "type": "number"
          },
          "item_bytes": {
            "type": "object",
            "properties": {
              "type": {
                "type": "number"
              },
              "data": {
                "type": "string"
              }
            }
          },
          "claimed": {
            "type": "boolean"
          },
          "claimed_bidders": {
            "type": "array"
          },
          "highest_bid_amount": {
            "type": "number"
          },
          "bids": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "auction_id": {
                  "type": "string",
                  "format": "uuid"
                },
                "bidder": {
                  "type": "string",
                  "format": "uuid"
                },
                "profile_id": {
                  "type": "string",
                  "format": "uuid"
                },
                "amount": {
                  "type": "number"
                },
                "timestamp": {
                  "type": "number",
                  "format": "int64"
                }
              }
            }
          }
        },
        "example": {
          "_id": "5dcdaf2244f4f4f350c02bf3",
          "uuid": "409a1e0f261a49849493278d6cd9305a",
          "auctioneer": "347ef6c1daac45ed9d1fa02818cf0fb6",
          "profile_id": "347ef6c1daac45ed9d1fa02818cf0fb6",
          "coop": [
            "347ef6c1daac45ed9d1fa02818cf0fb6"
          ],
          "start": 1573760802637,
          "end": 1573761102637,
          "item_name": "Azure Bluet",
          "item_lore": "§f§lCOMMON",
          "extra": "Azure Bluet Red Rose",
          "category": "blocks",
          "tier": "COMMON",
          "starting_bid": 1,
          "item_bytes": {
            "type": 0,
            "data": "H4sIAAAAAAAAAB2NQQqCQBhGv1ErHaKu0KoLtGtnarRIhTpA/OGfDIwZ4wxUF/IeHiyyto/3eBKIIJQEIDx4qsJaYJK07m6FhG+p9hEdVMV7TXU3Wh+JWaW6h6ZXhODYGg5/LeZDfxt6nZR5XhYhgoIaxmKE8dsZXu20YwuJZfa0hmJrjbo6y134f8pTll5O5TnbbgAP05Qaqhk+8AVIrd2eoAAAAA=="
          },
          "claimed": true,
          "claimed_bidders": [],
          "highest_bid_amount": 7607533,
          "bids": [
            {
              "auction_id": "409a1e0f261a49849493278d6cd9305a",
              "bidder": "99748e629dee463892f68abf3a780094",
              "profile_id": "99748e629dee463892f68abf3a780094",
              "amount": 7607533,
              "timestamp": 1573760824844
            }
          ]
        }
      },
      "SkyBlockProfile": {
        "properties": {
          "profile_id": {
            "type": "string",
            "format": "uuid"
          },
          "members": {
            "type": "object"
          },
          "community_upgrades": {
            "nullable": true,
            "type": "object"
          },
          "cute_name": {
            "type": "string"
          },
          "banking": {
            "nullable": true,
            "type": "object"
          },
          "game_mode": {
            "nullable": true,
            "type": "string"
          }
        }
      },
      "SkyBlockItem": {
        "properties": {
          "id": {
            "description": "The unique identifier for this item",
            "type": "string"
          },
          "material": {
            "description": "The Bukkit material enum value for the item",
            "type": "string"
          },
          "name": {
            "description": "The name of the item",
            "type": "string"
          },
          "tier": {
            "description": "The rarity tier of the item",
            "type": "string",
            "enum": [
              "COMMON",
              "UNCOMMON",
              "RARE",
              "EPIC",
              "LEGENDARY",
              "MYTHIC",
              "SUPREME",
              "SPECIAL",
              "VERY_SPECIAL"
            ]
          },
          "color": {
            "description": "The color metadata to be applied to an item, usually leather armor pieces",
            "pattern": "^(?:(?:^|,\\s*)([01]?\\d\\d?|2[0-4]\\d|25[0-5])){3}$",
            "type": "string"
          },
          "skin": {
            "description": "The skin value for a skull based item",
            "type": "string"
          }
        },
        "example": {
          "material": "LEATHER_CHESTPLATE",
          "color": "255,215,0",
          "name": "Farm Armor Chestplate",
          "category": "CHESTPLATE",
          "tier": "RARE",
          "stats": {
            "DEFENSE": 75,
            "HEALTH": 20
          },
          "npc_sell_price": 5200,
          "id": "FARM_ARMOR_CHESTPLATE"
        }
      },
      "Game": {
        "description": "Information about a specific game. When a field is not present you should fallback to the provided default if there is one, required fields will always exist.",
        "required": [
          "id",
          "name",
          "databaseName"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "description": "The backend ID of the game.",
            "example": 1
          },
          "name": {
            "type": "string",
            "description": "The display name of the game.",
            "example": "Bed Wars"
          },
          "databaseName": {
            "type": "string",
            "description": "The key used for database storage, such as for stats.",
            "example": "Bedwars"
          },
          "modeNames": {
            "type": "object",
            "description": "A map of mode key to display name",
            "example": {
              "solo_normal": "Solo",
              "team_normal": "Doubles"
            }
          },
          "retired": {
            "type": "boolean",
            "description": "True if the game is retired and no longer playable.",
            "default": false
          },
          "legacy": {
            "type": "boolean",
            "description": "True if the game is legacy and part of the Classic Lobby.",
            "default": false
          }
        },
        "example": {
          "id": 58,
          "name": "Bed Wars",
          "databaseName": "Bedwars",
          "modeNames": {
            "BEDWARS_TWO_FOUR": "4v4",
            "BEDWARS_EIGHT_ONE": "Solo"
          }
        }
      }
    }
  },
  "paths": {
    "/key": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "API Key Information",
        "security": [
          {
            "ApiKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "Get key information",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "record": {
                      "type": "object",
                      "properties": {
                        "key": {
                          "type": "string",
                          "format": "uuid"
                        },
                        "owner": {
                          "type": "string",
                          "format": "uuid"
                        },
                        "limit": {
                          "type": "integer",
                          "default": 120
                        },
                        "queriesInPastMin": {
                          "type": "integer"
                        },
                        "totalQueries": {
                          "type": "number"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/player": {
      "get": {
        "summary": "Data of a specific player, including game stats",
        "tags": [
          "Player Data"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get player's data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "player": {
                      "type": "object",
                      "properties": {
                        "uuid": {
                          "type": "string",
                          "example": "3fa85f6457174562b3fc2c963f66afa6"
                        },
                        "displayname": {
                          "type": "string",
                          "nullable": true
                        },
                        "rank": {
                          "type": "string",
                          "nullable": true,
                          "enum": [
                            "ADMIN",
                            "MODERATOR",
                            "HELPER",
                            "NORMAL"
                          ]
                        },
                        "packageRank": {
                          "type": "string",
                          "nullable": true,
                          "enum": [
                            "MVP_PLUS",
                            "MVP",
                            "VIP_PLUS",
                            "VIP",
                            "NONE"
                          ]
                        },
                        "newPackageRank": {
                          "type": "string",
                          "nullable": true,
                          "enum": [
                            "MVP_PLUS",
                            "MVP",
                            "VIP_PLUS",
                            "VIP",
                            "NONE"
                          ]
                        },
                        "monthlyPackageRank": {
                          "type": "string",
                          "nullable": true,
                          "enum": [
                            "SUPERSTAR",
                            "NONE"
                          ]
                        },
                        "firstLogin": {
                          "type": "number",
                          "nullable": true
                        },
                        "lastLogin": {
                          "type": "number",
                          "nullable": true
                        },
                        "lastLogout": {
                          "type": "number",
                          "nullable": true
                        },
                        "stats": {
                          "type": "object",
                          "nullable": true
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/friends": {
      "get": {
        "summary": "The friends of a specific player",
        "tags": [
          "Player Data"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get friends list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "uuid": {
                      "type": "string",
                      "format": "uuid",
                      "example": "ad8fefaa8351454bb739a4eaa872173f"
                    },
                    "records": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "_id": {
                            "type": "string"
                          },
                          "uuidSender": {
                            "type": "string",
                            "format": "uuid"
                          },
                          "uuidReceiver": {
                            "type": "string",
                            "format": "uuid"
                          },
                          "started": {
                            "type": "integer",
                            "format": "int64"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "422": {
            "$ref": "#/components/responses/MalformedData"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/recentgames": {
      "get": {
        "summary": "The recently played games of a specific player",
        "tags": [
          "Player Data"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get player's recent game",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "uuid": {
                      "type": "string",
                      "format": "uuid"
                    },
                    "games": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "date": {
                            "type": "number",
                            "format": "int64"
                          },
                          "gameType": {
                            "type": "string"
                          },
                          "mode": {
                            "type": "string"
                          },
                          "map": {
                            "type": "string"
                          },
                          "ended": {
                            "type": "number",
                            "format": "int64"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "422": {
            "$ref": "#/components/responses/MalformedData"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/status": {
      "get": {
        "summary": "The current online status of a specific player",
        "tags": [
          "Player Data"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get player status",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "uuid": {
                      "type": "string",
                      "format": "uuid",
                      "example": "ad8fefaa8351454bb739a4eaa872173f"
                    },
                    "session": {
                      "type": "object",
                      "properties": {
                        "online": {
                          "type": "boolean"
                        },
                        "gameType": {
                          "type": "string"
                        },
                        "mode": {
                          "type": "string"
                        },
                        "map": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/guild": {
      "get": {
        "summary": "Retrieve a Guild by a player, id, or name",
        "tags": [
          "Player Data"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "schema": {
              "type": "string",
              "format": "objectid"
            }
          },
          {
            "in": "query",
            "name": "player",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "in": "query",
            "name": "name",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Get guild information",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "guild": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/player/ranked/skywars": {
      "get": {
        "summary": "Ranked SkyWars data of a specific player",
        "tags": [
          "Player Data"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "description": "The UUID of the player you wish to request",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "SkyWars ranked rating and position.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "result": {
                      "type": "object",
                      "properties": {
                        "key": {
                          "type": "string",
                          "description": "A key built with the current month and year.",
                          "example": "7_21"
                        },
                        "position": {
                          "type": "number",
                          "description": "The position of the player on the leaderboards, this is not zero indexed and is the display position.",
                          "example": 50
                        },
                        "score": {
                          "type": "number",
                          "description": "The current score of the player for this season.",
                          "example": 2500
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "404": {
            "description": "No data could be found for the requested player.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "example": false
                    },
                    "cause": {
                      "type": "string",
                      "example": "No result was found"
                    }
                  }
                }
              }
            }
          },
          "422": {
            "$ref": "#/components/responses/MalformedData"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/resources/games": {
      "get": {
        "summary": "Game Information",
        "description": "Returns information about Hypixel Games. This endpoint is in early development and we are working to add more information when possible <a href=\"https://github.com/HypixelDev/PublicAPI/discussions/197#discussioncomment-1047648\">HypixelDev/PublicAPI#197</a>",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "games": {
                      "type": "object",
                      "description": "A map where the key is the backend name of the game",
                      "additionalProperties": {
                        "$ref": "#/components/schemas/Game"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/achievements": {
      "get": {
        "summary": "Achievements",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "achievements": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/challenges": {
      "get": {
        "summary": "Challenges",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "challenges": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/quests": {
      "get": {
        "summary": "Quests",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "quests": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/guilds/achievements": {
      "get": {
        "summary": "Guild Achievements",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "one_time": {
                      "type": "object"
                    },
                    "tiered": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/vanity/pets": {
      "get": {
        "summary": "Vanity Pets",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "types": {
                      "type": "object"
                    },
                    "rarities": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/vanity/companions": {
      "get": {
        "summary": "Vanity Companions",
        "tags": [
          "Resources"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "types": {
                      "type": "object"
                    },
                    "rarities": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/skyblock/collections": {
      "get": {
        "summary": "Collections",
        "description": "Information regarding Collections in SkyBlock",
        "tags": [
          "SkyBlock"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "version": {
                      "type": "string",
                      "example": "0.11.22"
                    },
                    "collections": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/skyblock/skills": {
      "get": {
        "summary": "Skills",
        "description": "Information regarding skills in SkyBlock",
        "tags": [
          "SkyBlock"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "version": {
                      "type": "string",
                      "example": "0.11.22"
                    },
                    "skills": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/skyblock/items": {
      "get": {
        "summary": "Items",
        "description": "Information regarding items in SkyBlock",
        "tags": [
          "SkyBlock"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/SkyBlockItem"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resources/skyblock/election": {
      "get": {
        "summary": "Election and Mayor",
        "description": "Information regarding the current mayor and ongoing election in SkyBlock",
        "tags": [
          "SkyBlock"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number"
                    },
                    "mayor": {
                      "type": "object",
                      "description": "Data regarding the current mayor"
                    },
                    "current": {
                      "type": "object",
                      "description": "Data regarding the current election, will not be provided if there is no open election ongoing"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/skyblock/news": {
      "get": {
        "summary": "News",
        "tags": [
          "SkyBlock"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "items": {
                      "items": {
                        "example": {
                          "item": {
                            "material": "DIAMOND"
                          },
                          "link": "https://hypixel.net",
                          "title": "SkyBlock v0.11",
                          "text": "15th January 2021"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/skyblock/auction": {
      "get": {
        "summary": "Request auction(s) by the auction UUID, player UUID, or profile UUID.",
        "tags": [
          "SkyBlock"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "description": "The auction UUID that you wish to request",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "player",
            "description": "The player UUID that you wish to request",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "profile",
            "description": "The profile UUID that you wish to request",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "auctions": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/SkyBlockAuction"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "422": {
            "$ref": "#/components/responses/MalformedData"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/skyblock/auctions": {
      "get": {
        "summary": "Active auctions",
        "tags": [
          "SkyBlock"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "number",
              "default": 0
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "page": {
                      "type": "number"
                    },
                    "totalPages": {
                      "type": "number",
                      "example": 32
                    },
                    "totalAuctions": {
                      "type": "number",
                      "example": 31267
                    },
                    "lastUpdated": {
                      "type": "number",
                      "format": "int64",
                      "example": 1571065561345
                    },
                    "auctions": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/SkyBlockAuction"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/MissingPage"
          },
          "422": {
            "$ref": "#/components/responses/InvalidPage"
          },
          "503": {
            "$ref": "#/components/responses/NotPopulated"
          }
        }
      }
    },
    "/skyblock/auctions_ended": {
      "get": {
        "summary": "Recently ended auctions",
        "description": "SkyBlock auctions which ended in the last 60 seconds.",
        "tags": [
          "SkyBlock"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number",
                      "format": "int64",
                      "example": 1607456463916
                    },
                    "auctions": {
                      "type": "array",
                      "items": {
                        "example": {
                          "auction_id": "015fe0c67e6041e69797bbe0c2725a21",
                          "seller": "fc76242bf64a4698ae0ebc136d900929",
                          "seller_profile": "85b96cd3e73e4580b8379162ec059141",
                          "buyer": "c1eff55de0d24ec6b44848799e9323ba",
                          "timestamp": 1607456400329,
                          "price": 190000,
                          "bin": true,
                          "item_bytes": "H4sIAAAAAAAAAEWR3W7TQBCFx2mBxKgtSH2ArUACZKL6L9jtndUYBdHQyGlV7qq1PXZX9U+03kB6yYNw7ffwo/AgiHEC4m7mmz1nz87qACPQhA4A2gAGItUGGjy5qNeV0nTYUzzX4PlNFUvkDzwuUNuD0Uyk+LHgeUOi3zo8S0WzKvjjCPYva4lDoofwsmu9KS95juesaxPDN+GY0FJJrHJ1v4PWxKTDAfGQy4rQB8M2WVKLqqHGy2RdsrKuGoWSPYiiaNjbS/yGBQ3RMo3+TF0Vj+/I5NXWj+2u7Acr0hCbmGbfbdWgd60/5xtmOBM4JPq5p9sofY43W4tfP3+wfyn/++Bfn+91nYJBxS0VlLQoMFGCIvYu6FnvXcenindtMQ++htMT8u11dPH1vWiYUFiyhFcsRiYxq2WO6Qm86NozUkRBFLLl7VU0HcL+F14iHNAg4rRuyYINgg5H4UZJHiglRbxW2AxhVEuRi+qa53CwnF0t7hY30cUsWIbD/jdBj4JP0zC6ozBkul4Teu34Tua7vj124tQduz73xtxOvbGVoZtMbN/xnIyMlSixUbxcwZFln/qn9DX2ue2wxRxgAE93q6b3wR9BYJa/RAIAAA=="
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/skyblock/bazaar": {
      "get": {
        "summary": "Bazaar",
        "description": "Returns the list of products along with their sell summary, buy summary and quick status.\n ### Product Description\n The returned product info has 3 main fields:\n - `buy_summary`\n - `sell_summary`\n - `quick_status`\n\n`buy_summary` and `sell_summary` are the current top 30 orders for each transaction type (in-game example: [Stock of Stonks](https://i.imgur.com/SjRONxq.png)).\n\n`quick_status` is a computed summary of the live state of the product (used for advanced mode view in the bazaar):\n- `sellVolume` and `buyVolume` are the sum of item amounts in all orders.\n - `sellPrice` and `buyPrice` are the weighted average of the top 2% of orders by volume.\n - `movingWeek` is the historic transacted volume from last 7d + live state.\n - `sellOrders` and `buyOrders` are the count of active orders. ",
        "tags": [
          "SkyBlock"
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "lastUpdated": {
                      "type": "number",
                      "format": "int64",
                      "example": 1590854517479
                    },
                    "products": {
                      "type": "object",
                      "example": {
                        "INK_SACK:3": {
                          "product_id": "INK_SACK:3",
                          "sell_summary": [
                            {
                              "amount": 20569,
                              "pricePerUnit": 4.2,
                              "orders": 1
                            },
                            {
                              "amount": 140326,
                              "pricePerUnit": 3.8,
                              "orders": 2
                            }
                          ],
                          "buy_summary": [
                            {
                              "amount": 640,
                              "pricePerUnit": 4.8,
                              "orders": 1
                            },
                            {
                              "amount": 640,
                              "pricePerUnit": 4.9,
                              "orders": 1
                            },
                            {
                              "amount": 25957,
                              "pricePerUnit": 5,
                              "orders": 3
                            }
                          ],
                          "quick_status": {
                            "productId": "INK_SACK:3",
                            "sellPrice": 4.2,
                            "sellVolume": 409855,
                            "sellMovingWeek": 8301075,
                            "sellOrders": 11,
                            "buyPrice": 4.99260315136572,
                            "buyVolume": 1254854,
                            "buyMovingWeek": 5830656,
                            "buyOrders": 85
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "503": {
            "$ref": "#/components/responses/NotPopulated"
          }
        }
      }
    },
    "/skyblock/profile": {
      "get": {
        "summary": "Profile by UUID",
        "description": "SkyBlock profile data, such as stats, objectives etc. The data returned can differ depending on the players in-game API settings.",
        "tags": [
          "SkyBlock"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "profile",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "profile": {
                      "$ref": "#/components/schemas/SkyBlockProfile"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "422": {
            "$ref": "#/components/responses/MalformedData"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/skyblock/profiles": {
      "get": {
        "summary": "Profiles by Player",
        "tags": [
          "SkyBlock"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "uuid",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "profiles": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/SkyBlockProfile"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/DataMissing"
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "422": {
            "$ref": "#/components/responses/MalformedData"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/boosters": {
      "get": {
        "summary": "Active Network Boosters",
        "tags": [
          "Other"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "Get boosters list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "boosters": {
                      "type": "array",
                      "items": {
                        "oneOf": [
                          {
                            "$ref": "#/components/schemas/ActiveBooster"
                          },
                          {
                            "$ref": "#/components/schemas/QueuedBooster"
                          }
                        ]
                      }
                    },
                    "boosterState": {
                      "type": "object",
                      "properties": {
                        "decrementing": {
                          "type": "boolean"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/counts": {
      "get": {
        "summary": "Current Player Counts",
        "tags": [
          "Other"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "playerCount": {
                      "type": "integer"
                    },
                    "games": {
                      "type": "object",
                      "example": {
                        "GAME_TYPE": {
                          "players": 2,
                          "modes": {
                            "mode_1": 1,
                            "mode_2": 1
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          }
        }
      }
    },
    "/leaderboards": {
      "get": {
        "summary": "Current Leaderboards",
        "tags": [
          "Other"
        ],
        "security": [
          {
            "ApiKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "leaderboards": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          },
          "503": {
            "$ref": "#/components/responses/NotPopulated"
          }
        }
      }
    },
    "/punishmentstats": {
      "get": {
        "tags": [
          "Other"
        ],
        "summary": "Punishment Statistics",
        "security": [
          {
            "ApiKey": []
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "watchdog_lastMinute": {
                      "type": "integer"
                    },
                    "staff_rollingDaily": {
                      "type": "integer"
                    },
                    "watchdog_total": {
                      "type": "integer"
                    },
                    "watchdog_rollingDaily": {
                      "type": "integer"
                    },
                    "staff_total": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/InvalidKey"
          },
          "429": {
            "$ref": "#/components/responses/RateLimited"
          },
          "503": {
            "$ref": "#/components/responses/NotPopulated"
          }
        }
      }
    }
  }
}